### PR TITLE
Update example F (libpmem to libpmem2)

### PR DESCRIPTION
**Pull request by DamianDuy**
This change is [Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @DamianDuy and @KFilipek)

___
*[examples/F/lowlevel.c, line 20 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4#-MlP3nCP5GsnjoDFsDaQ:-MlP3nCP5GsnjoDFsDaR:bd1dimg) ([raw file](https://github.com/pmemhackathon/2021-04-21/blob/ba3cf3fb8e18953882732ba07303bb2c99c127f1/examples/F/lowlevel.c#L20)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     int fd;
> 	char *mapaddr;
> 	size_t map_size;
> 	struct pmem2_config *cfg;
> 	struct pmem2_map *map;
> 	struct pmem2_source *src;
> 	pmem2_persist_fn persist;
> 	pmem2_memcpy_fn memcpy_fn;
> ```
</details>

set values, even if they will be nullptr's.
___
*[examples/F/README.txt, line 15 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4#-MlP4ezD0WGvvns7WIZg:-MlP4ezD0WGvvns7WIZh:b-et1oe3) ([raw file](https://github.com/pmemhackathon/2021-04-21/blob/ba3cf3fb8e18953882732ba07303bb2c99c127f1/examples/F/README.txt#L15)):*
> ```
> This example consists
> ```
Previous form was okey, know you have 2 verbs. 
Maybe "is example consisting of", but you should ask Lukasz Stolarczuk

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @DamianDuy, @grom72, and @KFilipek)

**Review by pbalcer — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4#-:-MlPGmpR3Dwf0rJxhdXN:bnfp4nl)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @grom72, @KFilipek, and @pbalcer)

___
*[examples/F/lowlevel.c, line 20 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4#-MlP3nCP5GsnjoDFsDaQ:-MlPCjswElLRXgzLGoYL:btgfaz1) ([raw file](https://github.com/pmemhackathon/2021-04-21/blob/ba3cf3fb8e18953882732ba07303bb2c99c127f1/examples/F/lowlevel.c#L20)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
>     int fd;
> 	char *mapaddr;
> 	size_t map_size;
> 	struct pmem2_config *cfg;
> 	struct pmem2_map *map;
> 	struct pmem2_source *src;
> 	pmem2_persist_fn persist;
> 	pmem2_memcpy_fn memcpy_fn;
> ```
set values, even if they will be nullptr's.
</blockquote></details>

I don't think that's necessary - they are never read uninitialized. And this is something that the compiler will warn about.
___
*[examples/F/README.txt, line 15 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4#-MlP4ezD0WGvvns7WIZg:-MlPEiNWE-t2ec5gqXvH:b-6g56ut) ([raw file](https://github.com/pmemhackathon/2021-04-21/blob/ba3cf3fb8e18953882732ba07303bb2c99c127f1/examples/F/README.txt#L15)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> This example consists
> ```
Previous form was okey, know you have 2 verbs. 
Maybe "is example consisting of", but you should ask Lukasz Stolarczuk
</blockquote></details>

Not sure if I understand.

You can either say:

`This is an example that consists of these files:`
or, as you say, "... example consisting of ..." (but that sounds odd to me, I think `consisting of` sounds best in sentences like 'example consisting of a and b will demonstrate ...")

or

`This example consists of these files:`

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

**Review by kilobyte — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4)* status: all files reviewed, 6 unresolved discussions (waiting on @DamianDuy and @KFilipek)

___
*[examples/F/lowlevel.c, line 20 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4#-MlP3nCP5GsnjoDFsDaQ:-MlRX5H67OVnQsbz3O9v:bq146rn) ([raw file](https://github.com/pmemhackathon/2021-04-21/blob/ba3cf3fb8e18953882732ba07303bb2c99c127f1/examples/F/lowlevel.c#L20)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

I don't think that's necessary - they are never read uninitialized. And this is something that the compiler will warn about.
</blockquote></details>

+1 — initializing to bogus values is worse than leaving uninitialized, as it stops the compiler warning.
___
*[examples/F/lowlevel.c, line 32 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4#-MlRXYdn1RWVT8tT_qXK:-MlRXYdn1RWVT8tT_qXL:b-glh3nl) ([raw file](https://github.com/pmemhackathon/2021-04-21/blob/ba3cf3fb8e18953882732ba07303bb2c99c127f1/examples/F/lowlevel.c#L32)):*
> ```C
> 
> 	/* Open file (create if it doesn't exist) from a file descriptor.
> 	 * User is responsible for handling files when using libpmem2.
> ```

The user
___
*[examples/F/lowlevel.c, line 33 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4#-MlRXclv9SIDZdArgmw_:-MlRXclv9SIDZdArgmwa:b-n2e3dg) ([raw file](https://github.com/pmemhackathon/2021-04-21/blob/ba3cf3fb8e18953882732ba07303bb2c99c127f1/examples/F/lowlevel.c#L33)):*
> ```C
> 	/* Open file (create if it doesn't exist) from a file descriptor.
> 	 * User is responsible for handling files when using libpmem2.
> 	*/
> ```

I'd separate this comment block from the open() clause — it refers to a larger part; if read as if pertaining to the `if` directly following it, it'd suggest opening "from" the file descriptor which is nonsense.
___
*[examples/F/lowlevel.c, line 96 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4#-MlRWEen0ELMn-MrRj5V:-MlRWEgM9MxUMiXjadp3:bhh0mgi) ([raw file](https://github.com/pmemhackathon/2021-04-21/blob/ba3cf3fb8e18953882732ba07303bb2c99c127f1/examples/F/lowlevel.c#L96)):*
> ```C
> 	 * Flush our string to persistence, libpmem2 automatically
> 	 * decides the correct mechanism for flushing the data
> 	 * onto the underlaying storage.
> ```

underlying — "underlay" is an active verb only
___
*[examples/F/README.txt, line 30 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4#-MlRWz5j-BORSdfhiHvc:-MlRWz5j-BORSdfhiHvd:bi76k2q) ([raw file](https://github.com/pmemhackathon/2021-04-21/blob/ba3cf3fb8e18953882732ba07303bb2c99c127f1/examples/F/README.txt#L30)):*
> ```help
> all up to the programmer. We use libpmem2 to cover the low-level
> boiler-plate code that sets required configuration and memory maps a file.
> The correct mechanism for flushing data onto the underlaying storage is
> ```

underlying

**Review by DamianDuy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @grom72, @KFilipek, and @kilobyte)

___
*[examples/F/lowlevel.c, line 32 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4#-MlRXYdn1RWVT8tT_qXK:-MlUTEbxEJlNKOW_fEX9:b-896fix) ([raw file](https://github.com/pmemhackathon/2021-04-21/blob/ba3cf3fb8e18953882732ba07303bb2c99c127f1/examples/F/lowlevel.c#L32)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

The user
</blockquote></details>

Done.
___
*[examples/F/lowlevel.c, line 33 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4#-MlRXclv9SIDZdArgmw_:-MlUTJOL48N2kGKJqO68:b-lcijbf) ([raw file](https://github.com/pmemhackathon/2021-04-21/blob/ba3cf3fb8e18953882732ba07303bb2c99c127f1/examples/F/lowlevel.c#L33)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

I'd separate this comment block from the open() clause — it refers to a larger part; if read as if pertaining to the `if` directly following it, it'd suggest opening "from" the file descriptor which is nonsense.
</blockquote></details>

Done. I changed this comment.
___
*[examples/F/lowlevel.c, line 96 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4#-MlRWEen0ELMn-MrRj5V:-MlUTdEX2UApI232RieU:b-896fix) ([raw file](https://github.com/pmemhackathon/2021-04-21/blob/ba3cf3fb8e18953882732ba07303bb2c99c127f1/examples/F/lowlevel.c#L96)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

underlying — "underlay" is an active verb only
</blockquote></details>

Done.
___
*[examples/F/README.txt, line 30 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4#-MlRWz5j-BORSdfhiHvc:-MlUTgNM-kYd_LjrJqJX:b-896fix) ([raw file](https://github.com/pmemhackathon/2021-04-21/blob/ba3cf3fb8e18953882732ba07303bb2c99c127f1/examples/F/README.txt#L30)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

underlying
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4#-:-Mp8Ecsh-r36FFzx7bba:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamianDuy)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamianDuy)

**Comment by lukaszstolarczuk** [comment]
@DamianDuy, if you want to continue work with this PR, please move it to the new base repository: https://github.com/pmemhackathon/hackathon

also, I believe it requires some Web content, to be displayed for this example (to be added on repo: https://github.com/pmemhackathon/hackathon.web)

**Pull request closed without merging**
