### PR TITLE
example R: add the librpma example

### PR DESCRIPTION
**Pull request by ldorau**
In this example we want to introduce to you a basic way of accessing
Persistent Memory when it is installed in a remote system.
Remote Persistent Memory (or RPMem for short) is a way of doing this
via a network by making use of the Remote Direct Memory Access (RDMA)
technology.

This example is an introduction to RPMem. We will guide you briefly through
setting up all required hardware and software components and verifying whether
the connection works properly. Having that, we will show you how to access
Persistent Memory on a remote system using the librpma library.

After completing this example you will know:
- what is RPMem and what it is good for,
- how RPMem is different comparing to PMem,
- what hardware and software components are required to start using RPMem,
- how to verify whether the RDMA network works properly,
- how to use librpma API to:
- establish a connection,
- prepare memory for remote manipulation,
- manipulate memory on the remote system,
- assure persistency of stores to the remote system.

Step-by-step you will:
- test the connection on the basic level using ping,
- test the connection RDMA capabilities using rping,
- review an application focusing on establishing a connection,
- review an application reading remote system's memory and writing it back
  in the persistent manner.

Co-authored-by: Oksana Salyk <oksana.salyk@intel.com>
Co-authored-by: Jan M Michalski <jan.m.michalski@intel.com>

Signed-off-by: Lukasz Dorau <lukasz.dorau@intel.com>

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/6)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/6)* status: 0 of 18 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/6)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`examples/R/common.c` line 100 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21/6#-NAxaTOO1MB5SfO1FXMB:-NAxaTOP6HbIqpuRbv5b:b-s3hmk9) ([raw file](https://github.com/pmemhackathon/2021-04-21/blob/6f20a1d07a4b5e4116f194b59c6a925e21073952/examples/R/common.c#L100)):*
> ```C
> 	ret = rpma_conn_req_connect(&req, pdata, conn_ptr);
> 	if (ret) {
> 		(void) rpma_conn_req_delete(&req);
> ```

Not needed.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/6)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[`examples/R/common.c` line 100 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21/6#-NAxaTOO1MB5SfO1FXMB:-NAxdt3wCS6DIHiMH7_H:b-896fix) ([raw file](https://github.com/pmemhackathon/2021-04-21/blob/6f20a1d07a4b5e4116f194b59c6a925e21073952/examples/R/common.c#L100)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/6#-:-NAxe5qk3q1MEkSMum7v:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/6#-:-NBBS7YRCc1AOI2akCKk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
@igchor please review and merge ;-)

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/6#-:-NBBiViJ-sXFRBcC1k51:b22qbjp)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by igchor — APPROVED** [review]
:lgtm: Could you please make a PR against https://github.com/pmemhackathon/hackathon similarly as for the web content?

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/6#-:-NBPnfk96ZnoGwuVD3aa:bgjk1yx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
@igchor We have nothing to submit to https://github.com/pmemhackathon/hackathon.

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21/6#-:-NBQRq6X4Ie2uhTcdLd9:bjkbpwc)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by ldorau** [comment]
Replaced with https://github.com/pmemhackathon/hackathon/pull/1

**Pull request closed without merging**
